### PR TITLE
Log the total number of files after filtering with the predicate

### LINKED ISSUE #13: Progress logging tracks against total files in directory, not files after prefiltering
**Describe the bug**
Astra UseCases provide the option to specify a prefilteringPredicate. This predicate is applied to the files in the directory that Astra runs over, and can be used to reduce the number of full ASTs that the tool needs to build. Where one is specified, and does filter out files from the target directory, Astra should reflect this in the progress logging, tracking against the total number of files *after filtering* with the predicate.

**To Reproduce**
1. Write an Astra UseCase which includes a prefilter
2. Run Astra with that UseCase over a directory, where the prefilter reduces the number of applicable files for Astra to run over.
4. Logging shown:
```
	INFO - 2401 .java files in directory to review
	INFO - Applying prefilters to files in directory
	INFO - 250 files remain after prefiltering
        INFO - [1%] complete, [25] of [2401] files reviewed
```

**Expected behavior**
Completion count should be of the files that pass the filter, not all files.
i.e. the final line of the logging should actually be:
```
        INFO - [10%] complete, [25] of [250] files reviewed
```

### PR DESCRIPTION
**Pull request by roch1**
- Resolves #13

### CODE REVIEW

**Comment by roch1** [comment]
Example from `ExampleUseCaseWithPrefilter`:

```
INFO - Counting files (this may take a few seconds)
INFO - 198 .java files in directory to review
INFO - Applying prefilters to files in directory
INFO - 5 files remain after prefiltering
INFO - [1%] complete, [2] of [5] files reviewed
...
INFO - [2%] complete, [4] of [5] files reviewed
...
```

**Comment by RadikalJin** [comment]
Hello, and thank you for your contribution to Astra! 

This looks like it could be a great fix for issue #13 - and it's nice to have an example of a prefiltering predicate in `astra-example`.

Just one issue - now that we've updated the total in the logs, it looks like the percentage completion should also be updated to track against the new total. It seems like we're still tracking against the original total - so even though the new total number of applicable files is 5, we're seeing 1/2% (presumably of 198), where we should be seeing 40/80% (2 as a percentage of 5, and 4 as a percentage of 5), like this:

```
INFO - [40%] complete, [2] of [5] files reviewed
...
INFO - [80%] complete, [4] of [5] files reviewed
```

Apologies for not making this clear when writing up the issue - I've updated the example with a percentage that reflects the new total.

**Comment by roch1** [comment]
@RadikalJin thanks for pointing that out, completely missed it

Output with percentage completed:
```
INFO - Counting files (this may take a few seconds)
INFO - 198 .java files in directory to review
INFO - Applying prefilters to files in directory
INFO - 5 files remain after prefiltering
INFO - [20%] complete, [1] of [5] files reviewed
INFO - [40%] complete, [2] of [5] files reviewed
INFO - [60%] complete, [3] of [5] files reviewed
...
INFO - [80%] complete, [4] of [5] files reviewed
INFO - [100%] complete, [5] of [5] files reviewed
INFO - Run complete in [0] seconds.
```

**Comment by RadikalJin** [comment]
Verified the same solution works with a rounded integer percentage:
```
INFO - Counting files (this may take a few seconds)
INFO - 849 .java files in directory to review
INFO - Applying prefilters to files in directory
INFO - 272 files remain after prefiltering
INFO - [1%] complete, [3] of [272] files reviewed
INFO - [2%] complete, [6] of [272] files reviewed
INFO - [3%] complete, [9] of [272] files reviewed
INFO - [4%] complete, [11] of [272] files reviewed
INFO - [5%] complete, [14] of [272] files reviewed
```

All looking good, thanks @roch1. Merging in now.

**Pull request merged**
